services:

  pg-db:
    image: postgres:16
    container_name: "postgres_db"
    restart: always

    volumes:
      - pg_volume:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DB}

volumes:
  pg_volume: